"""Cover-letter content dict -> .docx.

build_cover_letter() is the whole public surface, the sibling of
builder.build_resume(). The letter is the résumé's stationery: identical text
header (name, role line, mono contact line, coral rule), identical footer
(identity line and live page fields over the coral hairline), same fonts and
palette. Only the body is letter-shaped — correspondence-scale type, a date
line, a recipient block, salutation, paragraphs, and the fixed sign-off.

The sign-off is "Warmly," / Ryan on every letter — Ry's standing signature.
The YAML can override the strings, but the defaults are the convention.

Coral appears twice here (header rule, footer hairline). Slot 3 of
brand.CORAL_RATION — the section-heading underline — has no section headings
to land on, so a letter carries two of the three. The ration counts uses, and
unused is always allowed.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from docx import Document

from . import brand
# The header, footer, and page geometry are deliberately the résumé's own
# functions, not copies — if the résumé's stationery changes, the letter
# follows in the same edit. That coupling is the feature.
from .builder import _add_footer, _add_text_header, _setup_page
from .styles import build_letter_styles, build_styles

# Ry's standing sign-off. YAML may override, but never needs to.
DEFAULT_CLOSING = "Warmly,"
DEFAULT_SIGNATURE = "Ryan"


def _format_date(value) -> str:
    """August 18, 2026 — from a datetime.date, ISO string, or preformatted text."""
    if isinstance(value, date):
        return f"{value.strftime('%B')} {value.day}, {value.year}"
    text = str(value).strip()
    try:
        parsed = date.fromisoformat(text)
    except ValueError:
        return text                      # already prose ("August 18, 2026")
    return _format_date(parsed)


def build_cover_letter(content: dict, out_path: Path, *,
                       fonts: dict | None = None) -> Path:
    """content: a parsed letter YAML (meta + letter). Returns the written path."""
    meta = content["meta"]
    letter = content["letter"]
    variant = meta.get("variant", "eng")
    fonts = fonts or brand.FONT_SETS["brand"]

    if variant not in brand.ROLE_LINES:
        raise ValueError(f"unknown variant {variant!r}")
    if not letter.get("paragraphs"):
        raise ValueError("letter.paragraphs is empty — nothing to say")

    # Letters never run tight; the density levers are résumé page-count tools
    # and the letter metrics sit outside them by design.
    brand.apply_density("default")

    doc = Document()
    _setup_page(doc)
    build_styles(doc, fonts)
    build_letter_styles(doc, fonts)
    _add_text_header(doc, variant)

    dated = doc.add_paragraph(style="WP Letter Date")
    dated.add_run(_format_date(meta.get("date") or date.today()))

    for line in letter.get("recipient", []):
        p = doc.add_paragraph(style="WP Letter Recipient")
        p.add_run(line)

    salutation = doc.add_paragraph(style="WP Letter Salutation")
    salutation.add_run(letter.get("salutation", "Dear Hiring Team,"))

    for para in letter["paragraphs"]:
        p = doc.add_paragraph(style="WP Letter Body")
        p.add_run(para)

    closing = doc.add_paragraph(style="WP Letter Closing")
    closing.add_run(letter.get("closing", DEFAULT_CLOSING))

    signature = doc.add_paragraph(style="WP Letter Signature")
    signature.add_run(letter.get("signature", DEFAULT_SIGNATURE))

    _add_footer(doc, fonts, meta.get("footer_org", brand.CONTACT["org"]))

    props = doc.core_properties
    props.author = brand.CONTACT["name"]
    company = meta.get("company", "")
    props.title = (f"{brand.CONTACT['name']} — Cover Letter"
                   + (f" — {company}" if company else ""))
    subject = " · ".join(filter(None, [meta.get("role", ""), company]))
    props.subject = subject
    props.comments = (
        "Generated by ryan-resume-dev/resume_build/cover_letter.py — "
        "do not hand-edit; edit the letter YAML and rebuild."
    )

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(out_path))
    return out_path
